Weather
aayushmalde/FleetingBliss pull request #4
Opened 2021-08-01 18:40 UTC by aayushmalde

2021-08-02 13:35 UTC, MurliAShah commented on src/app/mainpage/mainpage.component.ts
> +  // countryMap: Map<string, CountryInfo> = new Map([
clean up all these comments

2021-08-02 13:35 UTC, MurliAShah commented on src/app/mainpage/mainpage.component.ts
> +    lattitude: 100,
Is this object used anywhere now?

2021-08-02 13:45 UTC, MurliAShah requested changes
Minor cleanup of old CountryInfo stuff (see my comments). Also, please rename longer named components to camel case and file names with hyphens (like HeaderCountry w/header-country), and rename mainpage to just main

2021-08-02 16:12 UTC, MurliAShah commented on src/app/weather/weather.component.ts
> +  constructor(private getWeatherService: weatherService, private countryNameService: CountryValuesService ) {}
It should be:
private **weatherService**: **W**eatherService, private countryNameService: Country**Name**Service

2021-08-02 18:38 UTC, MurliAShah commented on src/app/services/country-name.service.ts
>    countryValueObs: Subject<string> = new Subject();
Rename countryValueObs to countryNameSubject

2021-08-02 18:43 UTC, MurliAShah commented on src/app/services/weather.service.ts
> +    window.alert(errorMessage);
See if you can replace window.alert with Material snackbar (https://material.io/components/snackbars)

2021-08-02 18:47 UTC, MurliAShah commented on src/app/components/weather/weather.component.ts
> +                console.log('arr', this.temp_arr);
try to remove all console.log statements (and cleanup any commented code) before comitting

2021-08-03 09:45 UTC, MurliAShah commented on src/app/components/weather/weather.component.ts
> +  countryName$: Observable<string> | undefined; // convention to use $ at end for observables
remove my comments at end

2021-08-03 09:45 UTC, MurliAShah commented on src/app/components/weather/weather.component.ts
> +  countryName = 'Spain';
are you using 'app' and 'Spain' now?

2021-08-03 09:47 UTC, MurliAShah commented on src/app/components/weather/weather.component.ts
> +  temp_arr: Number[] = [];
Make more readable with more descriptive names like temperatures and descriptions (instead of temp_arr etc)

2021-08-03 09:49 UTC, MurliAShah commented on src/app/components/weather/weather.component.ts
> +              this.desc_arr?.push(
why is there ? here and next line (just been initialized in previous lines)

2021-08-03 09:51 UTC, MurliAShah commented on src/app/components/main/main.component.ts
> +export interface lodgingInfo {
Are lodgingInfo and activityInfo being used? Then make first letter uppercase and move to a model file

2021-08-03 09:55 UTC, MurliAShah commented on src/app/components/navigation/navigation.component.ts
>    europePlaces: string[] | undefined;
A lot is not being used... you want to stash (save up for later) and cleanup on GitHub?

2021-08-03 09:57 UTC, MurliAShah commented on src/app/components/main/main.component.html
> +  <div class="main">
header.ts is almost empty - better to move html into it (and for consistency)

2021-08-03 10:00 UTC, MurliAShah reviewed
header.ts is almost empty - better to move html into it (and for consistency with navigation)

2021-08-03 13:48 UTC, aayushmalde commented on src/app/components/weather/weather.component.ts
> +              this.desc_arr?.push(
earlier, the this.desc_arr=[] was not there so it did the ? automatically. It has been fixed

2021-08-03 13:51 UTC, aayushmalde commented on src/app/components/navigation/navigation.component.ts
>    europePlaces: string[] | undefined;
No, even if they are not functional I like them there for reference in the navigation. maybe later could remove but for now I would like to keep

2021-08-03 15:39 UTC, MurliAShah commented on src/app/components/weather/weather.component.ts
> +  temperatures: Number[] = [];
I thought we fixed these yesterday - should be lowercase number/string

2021-08-03 19:51 UTC, MurliAShah reviewed
Code looks much better! 

1. There are still some console.log statements checked in. 
2. Should it be called **place**Name  instead of countryName, since they are not all countries? (lot of renaming for this)

2021-08-04 17:26 UTC, MurliAShah commented on src/app/app.component.html
> +<!--Header: Website Name, Description, Photo-->
Cleanup first 2 commented out lines if not used

2021-08-04 17:31 UTC, MurliAShah reviewed
Removed commented out code in app.component.css and .html

2021-08-04 17:33 UTC, MurliAShah commented on src/app/components/main/main.component.html
> +    <div class="spain">
Rename css class (as it isn't for spain only)

2021-08-04 19:14 UTC, MurliAShah commented on src/app/components/weather/weather.component.html
> +    weatherInfo: weatherInfo$ | async
I thought we didn't need it anymore (after putting it inside the other's tap)?

2021-08-04 19:23 UTC, merged